import { ShiftLogEntry } from '../../domain/models';

interface ShiftLogEntryTemplate {
  tag: ShiftLogEntry['tags'][number];
  priority: ShiftLogEntry['priority'];
  bodyTemplate: (residentName: string, unit: string, extra?: string) => string;
  lineListSuggestion: boolean;
  symptomClass?: 'resp' | 'gi';
}

export const HASHTAG_SHIFT_LOG_MAP: Record<string, ShiftLogEntryTemplate> = {
  Isolation: {
    tag: 'Isolation',
    priority: 'Action Needed',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — Isolation precautions initiated. Review isolation type and confirm signage is in place.`,
    lineListSuggestion: false,
  },
  Outbreak: {
    tag: 'Outbreak',
    priority: 'Action Needed',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — Resident flagged for active outbreak. Verify line list entry and monitor for symptom progression.`,
    lineListSuggestion: true,
    symptomClass: 'resp',
  },
  Symptomatic: {
    tag: 'Outbreak',
    priority: 'Action Needed',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — New symptom onset reported. Assess for line list eligibility (ILI or GI). Notify charge nurse.`,
    lineListSuggestion: true,
    symptomClass: 'resp',
  },
  LabPending: {
    tag: 'Lab',
    priority: 'Action Needed',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — Lab specimen pending. Follow up for results and document in clinical record.`,
    lineListSuggestion: false,
  },
  NewAdmission: {
    tag: 'Isolation',
    priority: 'FYI',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — New admission. Review admission screening, vaccination status, and precaution requirements.`,
    lineListSuggestion: false,
  },
  ABT: {
    tag: 'ABT',
    priority: 'Action Needed',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — Antibiotic course active or initiated. Review ABT stewardship criteria and document indication.`,
    lineListSuggestion: false,
  },
  Education: {
    tag: 'Education',
    priority: 'FYI',
    bodyTemplate: (residentName, unit) =>
      `${residentName} (${unit}) — Education provided or pending. Document content and response.`,
    lineListSuggestion: false,
  },
};

const DEFAULT_TEMPLATE: ShiftLogEntryTemplate = {
  tag: 'Isolation',
  priority: 'FYI',
  bodyTemplate: (residentName, unit, extra) =>
    `${residentName} (${unit}) — Status update: ${extra ?? 'Unknown'}. Review and follow up as needed.`,
  lineListSuggestion: false,
};

export function buildHashtagShiftLogEntry(params: {
  hashtagValue: string;
  resident: { id: string; mrn: string; displayName: string; currentUnit?: string };
  facilityId: string;
  shift: ShiftLogEntry['shift'];
  outbreakRef?: { id: string; name: string };
  symptomClassOverride?: 'resp' | 'gi';
}): ShiftLogEntry {
  const template = HASHTAG_SHIFT_LOG_MAP[params.hashtagValue] ?? DEFAULT_TEMPLATE;
  const unit = params.resident.currentUnit ?? 'Unknown Unit';
  const body = template.bodyTemplate(params.resident.displayName, unit, params.hashtagValue);

  return {
    id: crypto.randomUUID(),
    facilityId: params.facilityId,
    createdAtISO: new Date().toISOString(),
    shift: params.shift,
    unit: params.resident.currentUnit,
    tags: [template.tag],
    priority: template.priority,
    body,
    residentRefs: [{ mrn: params.resident.mrn, name: params.resident.displayName }],
    outbreakRef: params.outbreakRef,
    sourceResidentHashtag: params.hashtagValue,
    autoGenerated: true,
  };
}

export function shouldSuggestLineList(hashtagValue: string): boolean {
  return HASHTAG_SHIFT_LOG_MAP[hashtagValue]?.lineListSuggestion ?? false;
}

export function getHashtagSymptomClass(
  hashtagValue: string,
  override?: 'resp' | 'gi',
): 'resp' | 'gi' | undefined {
  return override ?? HASHTAG_SHIFT_LOG_MAP[hashtagValue]?.symptomClass;
}
