import { useDatabase, useFacilityData } from '../app/providers';
import { ShiftLogEntry } from '../domain/models';
import {
  buildHashtagShiftLogEntry,
  shouldSuggestLineList,
  getHashtagSymptomClass,
} from '../features/ResidentBoard/hashtagToShiftLog';

interface UseHashtagShiftLogSyncParams {
  resident: { id: string; mrn: string; displayName: string; currentUnit?: string };
  currentShift: ShiftLogEntry['shift'];
  outbreakRef?: { id: string; name: string };
}

interface SyncResult {
  entryId: string;
  suggestsLineList: boolean;
  symptomClass?: 'resp' | 'gi';
}

export function useHashtagShiftLogSync(params: UseHashtagShiftLogSyncParams) {
  const { store, activeFacilityId } = useFacilityData();
  const { updateDB } = useDatabase();

  const syncHashtagToShiftLog = (
    hashtagValue: string,
    options?: { symptomClassOverride?: 'resp' | 'gi'; skipDuplicate?: boolean },
  ): SyncResult => {
    const skipDuplicate = options?.skipDuplicate !== false;
    const suggestsLineList = shouldSuggestLineList(hashtagValue);
    const symptomClass = getHashtagSymptomClass(hashtagValue, options?.symptomClassOverride);

    if (skipDuplicate) {
      const cutoff = Date.now() - 4 * 60 * 60 * 1000;
      const existing = Object.values(store.shiftLog ?? {}).find(
        (e): e is ShiftLogEntry =>
          (e as ShiftLogEntry).autoGenerated === true &&
          (e as ShiftLogEntry).sourceResidentHashtag === hashtagValue &&
          (e as ShiftLogEntry).residentRefs?.[0]?.mrn === params.resident.mrn &&
          new Date((e as ShiftLogEntry).createdAtISO).getTime() >= cutoff,
      );
      if (existing) {
        return { entryId: existing.id, suggestsLineList, symptomClass };
      }
    }

    const entry = buildHashtagShiftLogEntry({
      hashtagValue,
      resident: params.resident,
      facilityId: activeFacilityId,
      shift: params.currentShift,
      outbreakRef: params.outbreakRef,
      symptomClassOverride: options?.symptomClassOverride,
    });

    updateDB(draft => {
      const fd = draft.data.facilityData[activeFacilityId];
      if (!fd.shiftLog) fd.shiftLog = {};
      fd.shiftLog[entry.id] = entry;
    });

    return { entryId: entry.id, suggestsLineList, symptomClass };
  };

  return { syncHashtagToShiftLog };
}
