export type PdfOrientation = 'landscape' | 'portrait';

type CellValue = string | number | boolean | null | undefined;

export interface PdfTableSection {
  title?: string;
  columns: string[];
  rows: CellValue[][];
  pageBreakAfter?: boolean;
}

export interface ExportPdfOptions {
  title: string;
  orientation?: PdfOrientation;
  columns?: string[];
  rows?: CellValue[][];
  filters?: Record<string, string | number | boolean | null | undefined>;
  footerNote?: string;
  pageBreak?: boolean;
  tables?: PdfTableSection[];
}

const FACILITY_HEADER = [
  'Long Beach Nursing & Rehabilitation Center',
  'Infection Prevention & Antibiotic Stewardship Console',
];

const esc = (value: CellValue): string =>
  String(value ?? '—')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');

const buildTable = (table: PdfTableSection): string => {
  const headerHtml = table.columns.map((column) => `<th>${esc(column)}</th>`).join('');
  const bodyHtml = table.rows
    .map((row) => `<tr>${row.map((cell) => `<td>${esc(cell)}</td>`).join('')}</tr>`)
    .join('');

  return `
    <section class="report-section ${table.pageBreakAfter ? 'page-break' : ''}">
      ${table.title ? `<h3>${esc(table.title)}</h3>` : ''}
      <table>
        <thead><tr>${headerHtml}</tr></thead>
        <tbody>${bodyHtml}</tbody>
      </table>
    </section>
  `;
};

export const exportPDF = ({
  title,
  orientation = 'landscape',
  columns,
  rows,
  filters,
  footerNote,
  pageBreak,
  tables,
}: ExportPdfOptions): void => {
  const sections: PdfTableSection[] =
    tables && tables.length > 0
      ? tables
      : [
          {
            columns: columns ?? [],
            rows: rows ?? [],
            pageBreakAfter: pageBreak,
          },
        ];

  const filterText = Object.entries(filters ?? {})
    .filter(([, value]) => value !== null && value !== undefined && value !== '' && value !== 'all')
    .map(([key, value]) => `${key}: ${String(value)}`)
    .join(' | ');

  const printWindow = window.open('', '_blank', 'noopener,noreferrer,width=1200,height=800');
  if (!printWindow) return;

  const generatedOn = new Date().toLocaleString();
  const filename = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

  printWindow.document.write(`
    <!doctype html>
    <html>
      <head>
        <title>${esc(title)}</title>
        <style>
          @page { size: letter ${orientation}; margin: 0.45in; }
          body { font-family: Arial, sans-serif; color: #111827; font-size: 10px; }
          .header h1 { margin: 0; font-size: 12px; }
          .header h2 { margin: 2px 0 8px; font-size: 11px; font-weight: 600; }
          .meta { margin-bottom: 12px; color: #374151; }
          .meta p { margin: 2px 0; }
          h3 { margin: 0 0 6px; font-size: 11px; }
          .report-section { margin-bottom: 12px; }
          .page-break { page-break-after: always; }
          table { width: 100%; border-collapse: collapse; table-layout: fixed; }
          th, td { border: 1px solid #d1d5db; padding: 4px 6px; vertical-align: top; word-break: break-word; }
          th { background: #e5e7eb; text-align: left; }
          tbody tr:nth-child(even) td { background: #f9fafb; }
          .footer { position: fixed; left: 0.45in; right: 0.45in; bottom: 0.2in; display: flex; justify-content: space-between; color: #6b7280; font-size: 9px; }
        </style>
      </head>
      <body>
        <header class="header">
          <h1>${esc(FACILITY_HEADER[0])}</h1>
          <h2>${esc(FACILITY_HEADER[1])}</h2>
          <div class="meta">
            <p><strong>${esc(title)}</strong></p>
            <p>Date Generated: ${esc(generatedOn)}</p>
            <p>Filters Applied: ${esc(filterText || 'None')}</p>
          </div>
        </header>
        ${sections.map(buildTable).join('')}
        <footer class="footer">
          <span>Generated by IC Console</span>
          <span>${esc(footerNote || 'Page numbers available in print preview')}</span>
        </footer>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
  printWindow.onafterprint = () => printWindow.close();

  const link = document.createElement('a');
  link.download = `${filename || 'report'}.pdf`;
};
