import React, { useMemo, useState, useRef } from 'react';
import { useFacilityData } from '../../app/providers';
import { ResidentNote, ShiftLogEntry } from '../../domain/models';
import { SYMPTOM_HASHTAG_LIBRARY } from '../../utils/symptomHashtagLibrary';
import { getSymptomClassForHashtag } from '../../utils/symptomHashtagLibrary';
import { Download, Search, Filter } from 'lucide-react';
import { PrintButton } from '../../components/PrintButton';

export const SymptomWatchReport: React.FC = () => {
  const { store } = useFacilityData();
  const printRef = useRef<HTMLDivElement>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<'all' | 'notes' | 'shiftlog'>('all');
  const [filterDays, setFilterDays] = useState<number>(7);

  const allHashtags = useMemo(() => SYMPTOM_HASHTAG_LIBRARY.map(h => h.hashtag.toLowerCase()), []);

  const reportData = useMemo(() => {
    const data: Array<{
      id: string;
      date: string;
      type: 'Note' | 'Shift Log';
      residentName: string;
      unit: string;
      room: string;
      content: string;
      hashtags: string[];
      symptomClass: string;
    }> = [];

    const now = new Date();
    const cutoffDate = new Date(now.getTime() - filterDays * 24 * 60 * 60 * 1000);

    // Process Notes
    if (filterType === 'all' || filterType === 'notes') {
      Object.values(store.notes || {}).forEach((note: ResidentNote) => {
        const noteDate = new Date(note.createdAt);
        if (noteDate < cutoffDate) return;

        const lowerBody = note.body?.toLowerCase() || '';
        const words = lowerBody.split(/\s+/);
        const foundTags = new Set<string>();
        
        for (const word of words) {
          const cleanWord = word.replace(/[.,!?;:]+$/, '');
          if (allHashtags.includes(cleanWord) || cleanWord.startsWith('#')) {
             // We capture any hashtag, but specifically check against library
             foundTags.add(cleanWord);
          }
        }

        if (foundTags.size > 0) {
          const res = note.residentRef?.id ? store.residents?.[note.residentRef.id] : null;
          const symptomClasses = Array.from(foundTags).map(tag => getSymptomClassForHashtag(tag)).filter(Boolean);
          const uniqueClasses = Array.from(new Set(symptomClasses));

          data.push({
            id: note.id,
            date: note.createdAt,
            type: 'Note',
            residentName: res?.displayName || 'Unknown',
            unit: res?.currentUnit || 'Unknown',
            room: res?.currentRoom || 'Unknown',
            content: note.body,
            hashtags: Array.from(foundTags),
            symptomClass: uniqueClasses.join(', ') || 'Unknown',
          });
        }
      });
    }

    // Process Shift Logs
    if (filterType === 'all' || filterType === 'shiftlog') {
      Object.values(store.shiftLog || {}).forEach((log: ShiftLogEntry) => {
        const logDate = new Date(log.createdAtISO);
        if (logDate < cutoffDate) return;

        // Auto-generated shift logs from hashtags
        if (log.autoGenerated && log.sourceResidentHashtag) {
          const resName = log.residentRefs?.[0]?.name || 'Unknown';
          const symptomClass = getSymptomClassForHashtag(log.sourceResidentHashtag) || 'Unknown';
          
          data.push({
            id: log.id,
            date: log.createdAtISO,
            type: 'Shift Log',
            residentName: resName,
            unit: log.unit || 'Unknown',
            room: 'Unknown', // Shift logs don't store room directly
            content: log.body,
            hashtags: [log.sourceResidentHashtag],
            symptomClass,
          });
        }
      });
    }

    return data.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [store.notes, store.shiftLog, store.residents, filterDays, filterType, allHashtags]);

  const filteredData = useMemo(() => {
    return reportData.filter(item => {
      if (!searchTerm) return true;
      const term = searchTerm.toLowerCase();
      return (
        item.residentName.toLowerCase().includes(term) ||
        item.content.toLowerCase().includes(term) ||
        item.hashtags.some(h => h.toLowerCase().includes(term))
      );
    });
  }, [reportData, searchTerm]);

  const handleExport = () => {
    const rows = [
      ['Date', 'Type', 'Resident', 'Unit', 'Room', 'Hashtags', 'Symptom Class', 'Content']
    ];
    filteredData.forEach(item => {
      rows.push([
        new Date(item.date).toLocaleString(),
        item.type,
        item.residentName,
        item.unit,
        item.room,
        item.hashtags.join(' '),
        item.symptomClass,
        item.content.replace(/"/g, '""')
      ]);
    });

    const csv = rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `symptom_watch_report_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="no-print bg-white rounded-xl shadow-sm border border-neutral-200 p-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <h2 className="text-xl font-bold text-neutral-900">Symptom Watch & Hashtag Report</h2>
            <p className="text-sm text-neutral-500">Review detected hashtags from clinical notes and shift logs.</p>
          </div>
          <div className="flex items-center gap-3">
            <PrintButton contentRef={printRef} title="Symptom Watch Report" />
            <button
              onClick={handleExport}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-neutral-300 text-neutral-700 rounded-lg hover:bg-neutral-50 font-medium text-sm transition-colors"
            >
              <Download className="w-4 h-4" />
              Export CSV
            </button>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-4 mb-6 bg-neutral-50 p-4 rounded-lg border border-neutral-200">
          <div className="flex-1 relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400" />
            <input
              type="text"
              placeholder="Search residents, hashtags, or content..."
              value={searchTerm}
              onChange={e => setSearchTerm(e.target.value)}
              className="w-full pl-9 pr-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
            />
          </div>
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-neutral-500" />
            <select
              value={filterType}
              onChange={e => setFilterType(e.target.value as any)}
              className="border border-neutral-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 bg-white"
            >
              <option value="all">All Sources</option>
              <option value="notes">Clinical Notes</option>
              <option value="shiftlog">Shift Logs</option>
            </select>
            <select
              value={filterDays}
              onChange={e => setFilterDays(Number(e.target.value))}
              className="border border-neutral-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 bg-white"
            >
              <option value={1}>Last 24 Hours</option>
              <option value={3}>Last 3 Days</option>
              <option value={7}>Last 7 Days</option>
              <option value={14}>Last 14 Days</option>
              <option value={30}>Last 30 Days</option>
            </select>
          </div>
        </div>
        <div className="flex items-center justify-between">
            <span className="text-sm text-neutral-500">{filteredData.length} record{filteredData.length !== 1 ? 's' : ''} found</span>
        </div>
      </div>

      <div ref={printRef} className="space-y-6">
        <div className="hidden print:block text-center mb-6">
           <h2 className="text-xl font-bold">Symptom Watch Report</h2>
           <p className="text-sm text-neutral-500">Generated on {new Date().toLocaleDateString()}</p>
        </div>

        <div className="bg-white shadow rounded-lg overflow-hidden">
          <div className="px-4 py-5 sm:px-6 bg-indigo-50 border-b border-indigo-200">
            <h3 className="text-lg leading-6 font-bold text-indigo-900">Detected Symptoms & Hashtags</h3>
            <p className="text-xs text-indigo-700 mt-1">
              {filteredData.length} record{filteredData.length !== 1 ? 's' : ''} found
            </p>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-neutral-200 text-sm">
              <thead className="bg-neutral-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Date</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Source</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Resident</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Location</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Hashtags</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase">Class</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-neutral-500 uppercase w-1/3">Content Snippet</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-neutral-200">
                {filteredData.length > 0 ? (
                  filteredData.map(item => (
                    <tr key={item.id} className="hover:bg-neutral-50">
                      <td className="px-4 py-3 whitespace-nowrap text-neutral-500">
                        {new Date(item.date).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                          item.type === 'Note' ? 'bg-blue-50 text-blue-700' : 'bg-purple-50 text-purple-700'
                        }`}>
                          {item.type}
                        </span>
                      </td>
                      <td className="px-4 py-3 font-medium text-neutral-900">{item.residentName}</td>
                      <td className="px-4 py-3 text-neutral-500">
                        {item.unit} {item.room !== 'Unknown' ? `/ ${item.room}` : ''}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex flex-wrap gap-1">
                          {item.hashtags.map((tag, i) => (
                            <span key={i} className="px-2 py-0.5 bg-indigo-50 text-indigo-700 rounded text-xs font-medium">
                              {tag}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        {item.symptomClass !== 'Unknown' ? (
                          <span className="px-2 py-1 bg-neutral-100 text-neutral-700 rounded text-xs font-medium uppercase">
                            {item.symptomClass}
                          </span>
                        ) : (
                          <span className="text-neutral-400 text-xs">—</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-neutral-600">
                        <div className="line-clamp-2" title={item.content}>
                          {item.content}
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={7} className="px-4 py-8 text-center text-neutral-500">
                      No symptom watch records found for the selected filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};
